//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rouse.PatentCalculator.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Rouse.PatentCalculator.DomainModels;
    public partial class PatCalculatorEntities : DbContext
    {
        public PatCalculatorEntities()
            : base("name=PatCalculatorEntities")
        {
        }

        public PatCalculatorEntities(string connectionString)
            : base(connectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgencyFee> AgencyFees { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<OfficialFee> OfficialFees { get; set; }
        public virtual DbSet<PatentFee> PatentFees { get; set; }
        public virtual DbSet<PatentFeeType> PatentFeeTypes { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
    }
}
