//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rouse.PatentCalculator.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public int ID { get; set; }
        public string CountryCode { get; set; }
        public string Type { get; set; }
        public decimal Percentage { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
